server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    config:
      enabled: false
      import: optional:configserver:${CONFIG_URI:http://localhost:8888}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZOne: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    probes:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
