apiVersion: 1
contactPoints:
    - orgId: 1
      name: n11-slack
      receivers:
        - uid: eflj8jwfx2tq8d
          type: slack
          disableResolveMessage: false
          settings:
            url: ${SLACK_WEBHOOK_URL}
            title: '{{ .CommonLabels.alertname }}'
            text: |
              {{ range .Alerts -}}
              🚨 *{{ .Labels.alertname }}*
              *Summary:* {{ .Annotations.summary }}
              {{ end }}
  
