CREATE TABLE IF NOT EXISTS product_tags (
    product_id UUID NOT NULL REFERENCES products(id),
    tag_id     UUID NOT NULL REFERENCES tags(id),
    PRIMARY KEY (product_id, tag_id)
);

INSERT INTO product_tags (product_id, tag_id)
SELECT p.id, t.id FROM products p CROSS JOIN tags t
WHERE (p.slug, t.slug) IN (
    -- Elektronik
    ('kablosuz-kulaklik-bluetooth',     'elektronik'),
    ('kablosuz-kulaklik-bluetooth',     'ses'),
    ('kablosuz-kulaklik-bluetooth',     'kablosuz'),
    ('kablosuz-kulaklik-bluetooth',     'one-cikan'),
    ('mekanik-klavye-rgb',              'elektronik'),
    ('mekanik-klavye-rgb',              'bilgisayar-aksesuari'),
    ('mekanik-klavye-rgb',              'gaming'),
    ('usb-c-hub-7-in-1',                'elektronik'),
    ('usb-c-hub-7-in-1',                'bilgisayar-aksesuari'),
    ('usb-c-hub-7-in-1',                'yeni-urun'),
    ('akilli-telefon-256gb',            'elektronik'),
    ('akilli-telefon-256gb',            'premium'),
    ('akilli-telefon-256gb',            'one-cikan'),
    ('dizustu-bilgisayar-14-inc',       'elektronik'),
    ('dizustu-bilgisayar-14-inc',       'premium'),
    ('dizustu-bilgisayar-14-inc',       'bestseller'),
    ('akilli-saat-spor',                'elektronik'),
    ('akilli-saat-spor',                'fitness'),
    ('akilli-saat-spor',                'kablosuz'),
    ('kablosuz-kulakici-tws',           'elektronik'),
    ('kablosuz-kulakici-tws',           'ses'),
    ('kablosuz-kulakici-tws',           'bluetooth'),
    ('gaming-monitor-27',               'elektronik'),
    ('gaming-monitor-27',               'gaming'),
    ('gaming-monitor-27',               'premium'),
    ('bluetooth-hoparlor-tasinabilir',  'elektronik'),
    ('bluetooth-hoparlor-tasinabilir',  'ses'),
    ('bluetooth-hoparlor-tasinabilir',  'bluetooth'),
    ('harici-ssd-1tb',                  'elektronik'),
    ('harici-ssd-1tb',                  'bilgisayar-aksesuari'),
    ('kablosuz-mouse-ergonomik',        'elektronik'),
    ('kablosuz-mouse-ergonomik',        'bilgisayar-aksesuari'),
    ('kablosuz-mouse-ergonomik',        'kablosuz'),
    ('tablet-11-inc',                   'elektronik'),
    ('tablet-11-inc',                   'cocuk'),

    -- Moda
    ('klasik-beyaz-tisort',             'gunluk'),
    ('klasik-beyaz-tisort',             'erkek'),
    ('klasik-beyaz-tisort',             'kadin'),
    ('slim-fit-kot-pantolon',           'gunluk'),
    ('slim-fit-kot-pantolon',           'erkek'),
    ('kosu-rüzgarliği',                 'spor-giyim'),
    ('kosu-rüzgarliği',                 'kosu'),
    ('erkek-deri-ceket',                'erkek'),
    ('erkek-deri-ceket',                'premium'),
    ('spor-ayakkabi-koleksiyon',        'erkek'),
    ('spor-ayakkabi-koleksiyon',        'spor-giyim'),
    ('spor-ayakkabi-koleksiyon',        'bestseller'),
    ('kadin-deri-omuz-cantasi',         'kadin'),
    ('kadin-deri-omuz-cantasi',         'premium'),
    ('ipek-bluz-kadin',                 'kadin'),
    ('ipek-bluz-kadin',                 'premium'),
    ('midi-etek-kadin',                 'kadin'),
    ('midi-etek-kadin',                 'gunluk'),
    ('yazlik-elbise-cicekli',           'kadin'),
    ('yazlik-elbise-cicekli',           'yeni-urun'),
    ('erkek-chino-pantolon',            'erkek'),
    ('erkek-chino-pantolon',            'gunluk'),
    ('yun-kazak-unisex',                'gunluk'),
    ('yun-kazak-unisex',                'erkek'),
    ('yun-kazak-unisex',                'kadin'),
    ('beyzbol-sapkasi',                 'gunluk'),
    ('beyzbol-sapkasi',                 'spor-giyim'),

    -- Kitap & Müzik
    ('temiz-kod-clean-code',            'yazilim'),
    ('temiz-kod-clean-code',            'one-cikan'),
    ('temiz-kod-clean-code',            'bestseller'),
    ('designing-data-intensive-apps',   'yazilim'),
    ('designing-data-intensive-apps',   'mimari'),
    ('designing-data-intensive-apps',   'bestseller'),
    ('pragmatik-programci',             'yazilim'),
    ('pragmatik-programci',             'one-cikan'),
    ('domain-driven-design',            'yazilim'),
    ('domain-driven-design',            'mimari'),
    ('sapiens-yuval-noah-harari',       'bestseller'),
    ('suc-ve-ceza-dostoyevski',         'bestseller'),
    ('beyaz-dis-jack-london',           'cocuk'),
    ('vinyl-the-beatles-abbey-road',    'premium'),
    ('vinyl-pink-floyd-dark-side',      'premium'),
    ('akustik-gitar-baslangic',         'yeni-urun'),
    ('dijital-piyano-88-tus',           'premium'),
    ('roman-bestseller-set-5li',        'bestseller'),
    ('roman-bestseller-set-5li',        'indirimde'),

    -- Anne & Bebek
    ('bebek-arabasi-3-tekerlekli',      'bebek'),
    ('bebek-arabasi-3-tekerlekli',      'premium'),
    ('mama-sandalyesi-ahsap',           'bebek'),
    ('mama-sandalyesi-ahsap',           'one-cikan'),
    ('bebek-bezi-3lu-paket',            'bebek'),
    ('bebek-bezi-3lu-paket',            'bestseller'),
    ('biberon-seti-3lu',                'bebek'),
    ('bebek-battaniyesi-mussolin',      'bebek'),
    ('bebek-battaniyesi-mussolin',      'organik'),
    ('pelus-ayi-buyuk-boy',             'oyuncak'),
    ('pelus-ayi-buyuk-boy',             'cocuk'),
    ('lego-classic-yaratici',           'oyuncak'),
    ('lego-classic-yaratici',           'cocuk'),
    ('lego-classic-yaratici',           'bestseller'),
    ('bebek-bakim-cantasi',             'bebek'),
    ('bebek-tulumu-3lu',                'bebek'),
    ('bebek-tulumu-3lu',                'organik'),
    ('emzik-seti-2li',                  'bebek'),
    ('bebek-yatagi-park-besik',         'bebek'),
    ('oyuncak-arabalar-set',            'oyuncak'),
    ('oyuncak-arabalar-set',            'cocuk'),

    -- Ev & Yaşam
    ('organik-yesil-cay',               'organik'),
    ('organik-yesil-cay',               'mutfak'),
    ('sizma-zeytinyagi-500ml',          'organik'),
    ('sizma-zeytinyagi-500ml',          'mutfak'),
    ('sizma-zeytinyagi-500ml',          'indirimde'),
    ('led-masa-lambasi',                'dekorasyon'),
    ('led-masa-lambasi',                'yeni-urun'),
    ('seramik-saksi-3lu',               'dekorasyon'),
    ('seramik-saksi-3lu',               'indirimde'),
    ('kanepe-3-kisilik',                'dekorasyon'),
    ('kanepe-3-kisilik',                'premium'),
    ('yemek-takimi-12-parca',           'mutfak'),
    ('yemek-takimi-12-parca',           'one-cikan'),
    ('nevresim-takimi-cift-kisilik',    'dekorasyon'),
    ('kahve-makinesi-otomatik',         'mutfak'),
    ('kahve-makinesi-otomatik',         'premium'),
    ('blender-set-1500w',               'mutfak'),
    ('dekoratif-cerceve-set',           'dekorasyon'),
    ('el-yapimi-mum-sandal',            'dekorasyon'),
    ('el-yapimi-mum-sandal',            'organik'),

    -- Kozmetik
    ('hyaluronik-asit-serum',           'cilt-bakimi'),
    ('hyaluronik-asit-serum',           'kadin'),
    ('hyaluronik-asit-serum',           'bestseller'),
    ('mat-ruj-kirmizi',                 'makyaj'),
    ('mat-ruj-kirmizi',                 'kadin'),
    ('erkek-parfum-100ml',              'parfum'),
    ('erkek-parfum-100ml',              'erkek'),
    ('anti-aging-yuz-kremi',            'cilt-bakimi'),
    ('anti-aging-yuz-kremi',            'premium'),
    ('makyaj-fircasi-12li-set',         'makyaj'),
    ('makyaj-fircasi-12li-set',         'kadin'),
    ('gunes-kremi-spf50',               'cilt-bakimi'),
    ('gunes-kremi-spf50',               'bestseller'),
    ('goz-far-paleti-renkli',           'makyaj'),
    ('goz-far-paleti-renkli',           'kadin'),
    ('el-kremi-organik-shea',           'cilt-bakimi'),
    ('el-kremi-organik-shea',           'organik'),
    ('sampuan-volume-500ml',            'cilt-bakimi'),
    ('argan-yagi-100ml',                'cilt-bakimi'),
    ('argan-yagi-100ml',                'organik'),
    ('maskara-suya-dayanikli',          'makyaj'),
    ('maskara-suya-dayanikli',          'kadin'),
    ('kadin-parfum-50ml',               'parfum'),
    ('kadin-parfum-50ml',               'kadin'),
    ('kadin-parfum-50ml',               'premium'),

    -- Mücevher & Saat
    ('pirlanta-tek-tas-yuzuk',          'pirlanta'),
    ('pirlanta-tek-tas-yuzuk',          'premium'),
    ('pirlanta-tek-tas-yuzuk',          'kadin'),
    ('altin-kalp-kolye-14k',            'altin'),
    ('altin-kalp-kolye-14k',            'kadin'),
    ('altin-kalp-kolye-14k',            'bestseller'),
    ('gumus-bilezik-italyan',           'gumus'),
    ('gumus-bilezik-italyan',           'kadin'),
    ('mekanik-kol-saati-erkek',         'saat'),
    ('mekanik-kol-saati-erkek',         'erkek'),
    ('mekanik-kol-saati-erkek',         'premium'),
    ('spor-erkek-saati-cap',            'saat'),
    ('spor-erkek-saati-cap',            'erkek'),
    ('incili-kupe-klasik',              'gumus'),
    ('incili-kupe-klasik',              'kadin'),
    ('altin-bilezik-22-ayar',           'altin'),
    ('altin-bilezik-22-ayar',           'premium'),
    ('altin-bilezik-22-ayar',           'kadin'),
    ('pirlanta-kupe-rose-gold',         'pirlanta'),
    ('pirlanta-kupe-rose-gold',         'kadin'),
    ('pirlanta-kupe-rose-gold',         'altin'),
    ('nazar-kolye-altin',               'altin'),
    ('nazar-kolye-altin',               'one-cikan'),
    ('kadin-altin-saat',                'saat'),
    ('kadin-altin-saat',                'kadin'),
    ('gumus-tasli-yuzuk',               'gumus'),
    ('gumus-tasli-yuzuk',               'kadin'),
    ('altin-kelepce-bileklik',          'altin'),
    ('altin-kelepce-bileklik',          'premium'),

    -- Spor & Outdoor
    ('yoga-mati-6mm-tpe',               'yoga'),
    ('yoga-mati-6mm-tpe',               'fitness'),
    ('yoga-mati-6mm-tpe',               'bestseller'),
    ('kosu-ayakkabisi-air-yastik',      'kosu'),
    ('kosu-ayakkabisi-air-yastik',      'spor-giyim'),
    ('kosu-ayakkabisi-air-yastik',      'bestseller'),
    ('dambil-set-2x10kg',               'fitness'),
    ('kettlebell-16kg',                 'fitness'),
    ('spor-tisort-erkek-dryfit',        'spor-giyim'),
    ('spor-tisort-erkek-dryfit',        'erkek'),
    ('spor-corap-3lu',                  'spor-giyim'),
    ('kamp-cadiri-3-kisilik',           'kamp'),
    ('kamp-cadiri-3-kisilik',           'premium'),
    ('uyku-tulumu-mumya',               'kamp'),
    ('mountain-bike-26-jant',           'fitness'),
    ('mountain-bike-26-jant',           'premium'),
    ('silikon-tabanlik-spor',           'spor-giyim'),
    ('pilates-topu-65cm',               'yoga'),
    ('pilates-topu-65cm',               'fitness'),
    ('trekking-bot-su-gecirmez',        'kamp'),
    ('trekking-bot-su-gecirmez',        'premium'),

    -- Otomotiv & Motorsiklet
    ('motorsiklet-kaski-tam',           'motorsiklet'),
    ('motorsiklet-kaski-tam',           'premium'),
    ('aku-12v-60ah',                    'oto-aksesuar'),
    ('motor-yagi-5w-30-4lt',            'oto-aksesuar'),
    ('motor-yagi-5w-30-4lt',            'premium'),
    ('lastik-yaz-205-55-r16',           'oto-aksesuar'),
    ('silecek-takimi-set',              'oto-aksesuar'),
    ('oto-koltuk-kilifi-set',           'oto-aksesuar'),
    ('bagaj-kilifi-su-gecirmez',        'oto-aksesuar'),
    ('motor-eldiveni-yaz',              'motorsiklet'),
    ('arac-deri-kokulu',                'oto-aksesuar'),
    ('kit-lastik-anahtar-set',          'oto-aksesuar'),
    ('araba-cilasi-nano',               'oto-aksesuar'),
    ('araba-cilasi-nano',               'yeni-urun'),
    ('motor-tisort-erkek',              'motorsiklet'),
    ('motor-tisort-erkek',              'erkek')
)
ON CONFLICT (product_id, tag_id) DO NOTHING;
